version: '3'
services:
  db:
    container_name: db
    image: mariadb:10.6.12
    ports:
      - '3307:3306'
    environment:
      - MARIADB_DATABASE=icoop_system
      - MARIADB_USER=icoop
      - MARIADB_PASSWORD=icoop.cmcity.db@2023$
      - MARIADB_ROOT_PASSWORD=icoop.cmcity.db@2023$
      - MARIADB_ROOT_HOST=127.0.0.1
    volumes:
      - ./db-data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d

  app:
    build: .
    ports:
      - '8787:8787'
    depends_on:
      - db

volumes:
  db: