version: '3'
services:
  db:
    container_name: db
    image: mariadb:10.6.12
    ports:
      - '3307:3306'
    environment:
      - MARIADB_DATABASE=${DATABASE_HOST}
      - MARIADB_USER=${DATABASE_USER}
      - MARIADB_PASSWORD=${DATABASE_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MARIADB_ROOT_HOST=%
    volumes:
      - ./db-data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d

  app:
    build: .
    ports:
      - '8787:8787'
    depends_on:
      - db

volumes:
  db: