version: '3.8'
services:
  server:
    build: .
    restart: always
    ports:
      - '8787:8787'
    depends_on:
      - db
  db:
    container_name: db
    image: mariadb:10.6.5
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MARIADB_DATABASE=icoop_system
      - MARIADB_USER=root
      - MARIADB_PASSWORD=icoop.cmcity@2023
      - MARIADB_ROOT_PASSWORD=icoop.cmcity@2023
    volumes:
      - db:/var/lib/mysql

volumes:
  db: