server:
  connection-timeout: 300000
  servlet:
    session:
      context-parameters:
        request-timeout: 300000 # 5 minutes for the request processing time
      timeout: 10m
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  http2:
    enabled: true
  port: 8787
  tomcat:
    relaxed-query-chars: '|,{,},[,]'
    connection-timeout: 300000 # 5 minutes in milliseconds
    max-connections: 200 # Max number of connections
    max-threads: 200
  pathFile: '/app/upload'

spring:
  config:
    import: env.properties
  jackson:
    default-property-inclusion: non_null
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?characterEncoding=utf-8&useCompression=true&tcpKeepAlive=true&autocommit=false&profileSQL=true
#    username: ${DATABASE_USER}
#    password: ${DATABASE_PASSWORD}
    url: jdbc:mariadb://127.0.0.1:3306/icoop_system?characterEncoding=utf-8&useCompression=true&tcpKeepAlive=true&autocommit=false&profileSQL=true
    username: root
    password: root
    hikari:
      auto-commit: false
      maximum-pool-size: 20
    initialization-mode: always
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-circular-references: true
    headless: true
  mail:
    host: ${MAIL_HOST}
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    port: ${MAIL_PORT}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  mvc:
    async:
      request-timeout: 300000
management:
  endpoints:
    web:
      exposure:
        include: mappings