server:
  http2:
    enabled: true
  port: 8787
  tomcat:
    relaxed-query-chars: '|,{,},[,]'

spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/welfare_cm_city?characterEncoding=utf-8&useCompression=true&tcpKeepAlive=true&autocommit=false&profileSQL=true
    username: root
    password: root
    hikari:
      auto-commit: false
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-circular-references: true
  mail:
    host: smtp.gmail.com
    username: sound.nature.v1@gmail.com
    password: azvjeqcptynijxng
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
#    scheduler:
#      persistence:
#        enabled: true
#        redis:
#          embedded: true
#          enabled: false

management:
  endpoints:
    web:
      exposure:
        include: mappings
